function disassemble-symbol {(
    set -eu
    local re_symbol="$1" obj="$2"

    local out="$(/bin/realpath -s "$2")" c_symbol cxx_symbol
    local out_prefix="${out%o}"
    local re_filter_out='^[[:space:]]*$|^Disassembly of section |^/[^:]+:[[:space:]]+file format'

    local objdump=(objdump --{disassembler-color,visualize-jumps}=color -Mintel -C)
    (( ${S:-0} < 1 )) || objdump+=(-lS) # S=1 includes source code.

    paste <(nm -jU "$obj") <(nm -jUC "$obj") | egrep -e "$re_symbol" | while IFS=$'\t' read c_symbol cxx_symbol; do
        out="${out_prefix}${c_symbol}.S"
        ( (( ${V:-0} < 1 )) || set -x; ${objdump[@]} --disassemble="$cxx_symbol" "$obj" ) | egrep -ve "$re_filter_out" > "$out"
        echo "$out: $cxx_symbol"
    done
)}

function create_system_config_mk {(
    set -eu
    cat <<EOF
# Generated by ${FUNCNAME[0]} in ${BASH_SOURCE[0]}.
override has_system_config := 1

chrt_fifo := $(chrt -f 50 echo -n 'chrt' || echo -n 'sudo chrt') -f 50
uname_m := $(uname -m)
use_ld := -fuse-ld=$(type -p lld &> /dev/null && echo -n lld || echo -n bfd)
EOF
)}
