name: Meson Continuous Integrations

on:
  push:
    branches: [ master, maxim ]
    paths:
      - '**.h'
      - '**.cc'
      - 'meson*'
      - .github/workflows/ci-meson.yml
  pull_request:
    branches: [ master ]
    paths:
      - '**.h'
      - '**.cc'
      - 'meson*'
      - .github/workflows/ci-meson.yml

defaults:
  run:
    shell: bash

env:
  # Enable printf thousand separators.
  LC_NUMERIC: en_US.UTF-8

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, ubuntu-26.04, ubuntu-26.04-arm]
        cpp_compiler: [g++, clang++]

    name: ${{ matrix.os }}, ${{ matrix.cpp_compiler }}
    runs-on: ${{ matrix.os }}

    env:
      CXX: ${{ matrix.cpp_compiler }}

    steps:
      - uses: actions/checkout@v7

      - name: Install Meson and Boost.Test
        run: |
          sudo apt-get update
          sudo apt-get install --yes -qq meson libboost-test-dev

      - name: Environment info
        run: |
          env | sort --ignore-case
          echo "n_proc=$(nproc)" >> "$GITHUB_ENV"
          cat /proc/cpuinfo

      - name: Unit-test
        run: |
          meson setup build1 -Dwerror=true -Dwarning_level=2
          meson compile -vC build1
          meson test -vC build1

      - name: Unit-test with address sanitizer
        run: |
          meson setup build2 -Dwerror=true -Dwarning_level=2 -Db_sanitize=address
          meson compile -vC build2
          meson test -vC build2

      - name: Unit-test with undefined sanitizer
        run: |
          meson setup build3 -Dwerror=true -Dwarning_level=2 -Db_sanitize=undefined
          meson compile -vC build3
          meson test -vC build3

      - name: Unit-test with thread sanitizer
        run: |
          meson setup build4 -Dwerror=true -Dwarning_level=2 -Db_sanitize=thread
          meson compile -vC build4
          meson test -vC build4

      - name: Benchmark
        if: ${{ env.n_proc > 1 }}
        run: |
          ulimit -Sl unlimited
          sudo sysctl kernel.sched_rt_runtime_us=-1
          meson setup build5 -Dwerror=true -Dwarning_level=2 -Dbenchmarks_min=true -Dtests=false
          meson compile -vC build5
          sudo chrt -f 50 meson test -vC build5 --benchmark
