name: Makefile Continuous Integrations

on:
  push:
    branches: [ master, maxim ]
    paths:
      - '!**'
      - '**.h'
      - '**.cc'
      - Makefile
      - .github/workflows/ci.yml
  pull_request:
    branches: [ master ]
    paths:
      - '!**'
      - '**.h'
      - '**.cc'
      - Makefile
      - .github/workflows/ci.yml

defaults:
  run:
    shell: bash

jobs:
  unit-test:
    strategy:
      fail-fast: false
      matrix:
        toolset: [gcc, clang]
        os: [ubuntu-22.04, ubuntu-24.04, ubuntu-22.04-arm, ubuntu-24.04-arm]

    runs-on: ${{ matrix.os }}

    env:
      make: make -R TOOLSET=${{ matrix.toolset }}

    steps:
    - uses: actions/checkout@v7

    - name: Install Boost.Test
      run: |
        sudo apt-get update
        sudo apt-get install --yes -qq libboost-test-dev

    - name: Environment variables
      run: ${{ env.make }} env

    - name: Toolset versions
      run: ${{ env.make }} versions

    - name: Build and run unit tests
      run: ${{ env.make }} run_example run_tests

    - name: Build and run unit tests with address sanitizer
      run: ${{ env.make }} BUILD=sanitize2 run_example run_tests

    - name: Build and run unit tests with thread sanitizer
      run: ${{ env.make }} BUILD=sanitize run_example run_tests
