name: Makefile Continuous Integrations

on:
  push:
    branches: [ master, maxim ]
    paths:
      - '**.h'
      - '**.cc'
      - Makefile
      - .github/workflows/ci.yml
  pull_request:
    branches: [ master ]
    paths:
      - '**.h'
      - '**.cc'
      - Makefile
      - .github/workflows/ci.yml

defaults:
  run:
    shell: bash

env:
  # Enable printf thousand separators.
  LC_NUMERIC: en_US.UTF-8

jobs:
  unit-test:
    strategy:
      fail-fast: false
      matrix:
        toolset: [gcc, clang]
        os: [ubuntu-22.04, ubuntu-22.04-arm, ubuntu-24.04, ubuntu-24.04-arm, ubuntu-26.04, ubuntu-26.04-arm]

    name: ${{ matrix.os }}, ${{ matrix.toolset }}
    runs-on: ${{ matrix.os }}

    # The worst empirical run-time of this job is about 2m30s.
    timeout-minutes: 5

    env:
      make: make -R TOOLSET=${{ matrix.toolset }}

    steps:
    - uses: actions/checkout@v7

    - name: Install Boost.Test
      run: |
        sudo apt-get update
        sudo apt-get install --yes -qq libboost-test-dev

    - name: Environment info
      id: ei
      run: |
        ${{ env.make }} env
        echo "n_proc=$(nproc)" >> "$GITHUB_OUTPUT"
        cat /proc/cpuinfo

    - name: Toolset versions
      run: ${{ env.make }} versions

    - name: Unit-test
      run: ${{ env.make }} -j${{ steps.ei.outputs.n_proc }} run_ci

    - name: Unit-test with address sanitizer
      run: ${{ env.make }} -j${{ steps.ei.outputs.n_proc }} BUILD=sanitize2 run_ci

    - name: Unit-test with thread sanitizer
      run: ${{ env.make }} -j${{ steps.ei.outputs.n_proc }} BUILD=sanitize run_ci

    - name: Benchmark
      if: ${{ steps.ei.outputs.n_proc > 1 }}
      run: |
        ulimit -Sl unlimited
        sudo sysctl kernel.sched_rt_runtime_us=-1
        ${{ env.make }} -j${{ steps.ei.outputs.n_proc }} run_benchmarks_ci
